apiVersion: v1
kind: Namespace
metadata:
  name: my-nginx-0gsr8g
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-0gsr8g
  namespace: my-nginx-0gsr8g
  labels:
    name: nginx-0gsr8g
spec:
  replicas: 1
  selector:
    matchLabels:
      name: nginx-0gsr8g
  template:
    metadata:
      namespace: my-nginx-0gsr8g
      labels:
        name: nginx-0gsr8g
    spec:
      containers:
      - name: nginx-0gsr8g
        image: nginx
        ports:
        - containerPort: 80

